---
name: Arun Aqua
on: null
push: null
branches:
  - main
jobs: null
greet: null
runs-on: ubuntu-latest
steps:
  - name: Say hello to users
    run: echo "hello dosto"
  - name: Say hello to username
    run: echo "hello to username"
