---
name: Hello Arun Aqua
on: null
push: null
branches:
  - main
jobs: null
greet: null
runs-on: ubuntu-latest
steps:
  - name: Say hello
    run: echo "hello dosto"
  - name: Say hello to username
    run: echo "hello Arun"
details:
runs-on: ubuntu-latest
  steps:
    - name: show what is the version of python and docker
      run: docker ---version && python --version
